aptitude-robot-session: Abort if APT was not able to fetch all repositories

diff --git a/aptitude-robot-session b/aptitude-robot-session
--- a/aptitude-robot-session
+++ b/aptitude-robot-session
@@ -59,7 +59,14 @@ export DEBIAN_PRIORITY
 
 # -q (for --quiet) suppresses percentage reporting for downloads
 # but leaves most regular output to be collected in the log file
-/usr/bin/aptitude -q update && touch /var/lib/apt/update_success
+/usr/bin/aptitude -q update
+
+if egrep -q '[EW]: Failed to fetch ' "$LOG_SESSION"; then
+    echo "E: aptitude-robot failed to fetch some APT repositories. Aborting."
+    exit 2
+fi
+
+touch /var/lib/apt/update_success
 
 /usr/sbin/aptitude-robot -y -q "$@" \
     -o DPkg::Options::=--force-confdef \
